package com.mygdx.hadal.utils;

import com.mygdx.hadal.managers.GameStateManager;

import java.util.ArrayList;

/**
 * why did I make this
 * @author Himpanzee Hanicotti
 */
public enum NameGenerator {
	
	//starting consonants. funnier sounding ones have higher frequencies.
	B_START("b", "b_first", 4, "start"),
	C_START("c", "c_first", 2, "start"),
	D_START("d", "d_first", 2, "start"),
	F_START("f", "f_first", 3, "start"),
	G_START("g", "g_first", 3, "start"),
	H_START("h", "h_first", 2, "start"),
	J_START("j", "j_first", "start"),
	K_START("k", "k_first", "start"),
	L_START("l", "l_first", 2, "start"),
	M_START("m", "m_first", 2, "start"),
	N_START("n", "n_first", 2, "start"),
	P_START("p", "p_first", 2, "start"),
	QU_START("qu", "qu_first", "start"),
	R_START("r", "r_first", 2, "start"),
	S_START("s", "s_first", 4, "start"),
	T_START("t", "t_first", 3, "start"),
	V_START("v", "v_first", "start"),
	W_START("w", "w_first", "start"),
	X_START("x", "x_first", "start"),
	Y_START("y", "y_first", "start"),
	Z_START("z", "z_first", "start"),
	
	//second consonant possibilities for things like 'ch', and 'sp'
	C_NEXT("c", "c_next", "s_first"),
	H_NEXT("h", "h_next", "c_first", "g_first", "p_first", "s_first", "t_first", "w_first"),
	K_NEXT("k", "k_next", "s_first"),
	L_NEXT("l", "l_next", "b_first", "c_first", "f_first", "g_first", "k_first", "p_first", "s_first", "v_first"),
	M_NEXT("m", "m_next", "s_first"),
	N_NEXT("n", "n_next", "g_first", "s_first"),
	P_NEXT("p", "p_next", "s_first"),
	Q_NEXT("qu", "qu_next", "s_first"),
	R_NEXT("r", "r_next", "b_first", "c_first", "d_first", "f_first", "g_first", "k_first", "p_first", "t_first", "w_first"),
	T_NEXT("t", "t_next", "s_first"),
	V_NEXT("v", "v_next", "s_first"),
	W_NEXT("w", "w_next", "s_first", "t_first"),
	
	//this is a transition unit that follows the first consonant(s).
	CONSONANT_FIRST("", "consonant_first", "b_first", "c_first", "d_first" , "f_first" , "g_first", "h_first", "j_first", "k_first", "l_first", "m_first", "n_first", "p_first", "qu_first", "r_first", "s_first", "t_first", "v_first", "w_first", "x_first", "y_first", "z_first"),
	CONSONANT_NEXT("", "consonant_next", "c_next", "h_next", "k_next", "l_next", "m_next", "n_next", "p_next", "qu_next", "r_next", "t_next", "v_next", "w_next"),
	
	//this is a vowel that can follow either starting consonant type
	A_VOWEL("a", "a_first", "consonant_first", "consonant_next"),
	E_VOWEL("e", "e_first", "consonant_first", "consonant_next"),
	I_VOWEL("i", "i_first", "consonant_first", "consonant_next"),
	O_VOWEL("o", "o_first", "consonant_first", "consonant_next"),
	U_VOWEL("u", "u_first", "consonant_first", "consonant_next"),
	
	//this is a transition that follows the first vowel in the name
	VOWEL_FIRST("", "vowel_first", "a_first", "e_first", "i_first", "o_first", "u_first"),
	
	//the weights of these transitions are used to balance probability between names that have long suffixes vs names where each digram is procedurally generated
	A_ANY("", "a", 7, "a_first", "a_next"),
	E_ANY("", "e", 7, "e_first", "e_next"),
	I_ANY("", "i", 7, "i_first", "i_next"),
	O_ANY("", "o", 7, "o_first", "o_next"),
	U_ANY("", "u", 7, "u_first", "u_next"),
	
	//after any 'universal' digram, we have the option to stick another vowel afterwards for a second name segment.
	A_NEXT("a", "a_next", 50, "universal"),
	E_NEXT("e", "e_next", 50, "universal"),
	I_NEXT("i", "i_next", 50, "universal"),
	O_NEXT("o", "o_next", 50, "universal"),
	U_NEXT("u", "u_next", 50, "universal"),
	
	//These are digrams that end segments. They can end the name or be followed up with a suffix or another syllable.
	B2("b", "b2", "vowel_first"),
	BB("bb", "bb", "vowel_first"),
	B_("", "b_", "b2", "bb"),

	C2("c", "c2", "vowel_first"),
	CC("cc", "cc", "vowel_first"),
	CH("ch", "ch", "vowel_first"),
	CK("ck", "ck", "vowel_first"),
	CT("ct", "ct", "vowel_first"),
	C_("", "c_", "c2", "cc", "ch", "ck", "ct"),
	
	D2("d", "d2", "vowel_first"),
	DD("dd", "dd", "vowel_first"),
	D_("", "d_", "d2", "dd"),

	F2("f", "f2", "vowel_first"),
	FF("ff", "ff", "vowel_first"),
	FT("ft", "ft", "vowel_first"),
	F_("", "f_", "f2", "ff", "ft"),

	G2("g", "g2", "vowel_first"),
	GG("gg", "gg", 5, "vowel_first"),
	G_("", "g_", "g2", "gg"),

	H2("h", "h_", "vowel_first"),

	J2("j", "j_", "vowel_first"),

	K2("k", "k_", "vowel_first"),

	L2("l", "l2", "vowel_first"),
	LB("lb", "lb", "vowel_first"),
	LC("lc", "lc", "vowel_first"),
	LD("ld", "ld", 3, "vowel_first"),
	LF("lf", "lf", 3, "vowel_first"),
	LG("lg", "lg", 3, "vowel_first"),
	LM("lm", "lm", "vowel_first"),
	LN("ln", "ln", "vowel_first"),
	LP("lp", "lp", 3, "vowel_first"),
	LT("lt", "lt", 2, "vowel_first"),
	LV("lv", "lv", "vowel_first"),
	LZ("lz", "lz", "vowel_first"),
	L_("", "l_", "l2", "lb", "lc", "ld", "lf", "lg", "lm", "ln", "lp", "lt", "lv", "lz"),

	M2("m", "m2", "vowel_first"),
	MB("mb", "mb", "vowel_first"),
	MM("mm", "mm", "vowel_first"),
	MP("mp", "mp", 3, "vowel_first"),
	MS("ms", "ms", "vowel_first"),
	M_("", "m_", "vowel_first"),

	N2("n", "n2", "vowel_first"),
	NC("nc", "nc", "vowel_first"),
	ND("nd", "nd", 2, "vowel_first"),
	NG("ng", "ng", 3, "vowel_first"),
	NJ("nj", "nj", "vowel_first"),
	NK("nk", "nk", 3, "vowel_first"),
	NP("np", "np", "vowel_first"),
	NS("ns", "ns", "vowel_first"),
	NT("nt", "nt", "vowel_first"),
	NX("nx", "nx", "vowel_first"),
	NZ("nz", "nz", "vowel_first"),
	N_("", "n_", "n2", "nc", "nd", "ng", "nj", "nk", "np", "ns", "nt", "nx", "nz"),

	P2("p", "p2", "vowel_first"),
	PP("pp", "pp", 2, "vowel_first"),
	P_("", "p_", "p2", "pp"),

	R2("r", "r2", "vowel_first"),
	RB("rb", "rb", 2, "vowel_first"),
	RC("rb", "rc", "vowel_first"),
	RD("rd", "rd", 2, "vowel_first"),
	RF("rf", "rf", 2, "vowel_first"),
	RG("rg", "rg", 2, "vowel_first"),
	RJ("rj", "rj", "vowel_first"),
	RK("rk", "rk", 2, "vowel_first"),
	RL("rl", "rl", "vowel_first"),
	RM("rm", "rm", "vowel_first"),
	RN("rn", "rn", "vowel_first"),
	RP("rp", "rp", 2, "vowel_first"),
	RR("rr", "rr", 2, "vowel_first"),
	RS("rs", "rs", "vowel_first"),
	RT("rt", "rt", 2, "vowel_first"),
	RV("rv", "rv", "a", "vowel_first"),
	RX("rx", "rx", "vowel_first"),
	RZ("rz", "rz", "vowel_first"),
	R_("", "r_", "r2", "rb", "rc", "rd", "rf", "rg", "rj", "rk", "rl", "rm", "rn", "rp", "rr", "rs", "rt", "rv", "rx", "rz"),

	S2("s", "s2", "vowel_first"),
	SH("sh", "sh", 2, "vowel_first"),
	SK("sk", "sk", "vowel_first"),
	SP("sp", "sp", "vowel_first"),
	SS("ss", "ss", "vowel_first"),
	ST("st", "st", "vowel_first"),
	S_("", "s_", "s2", "sh", "sk", "sp", "ss", "st"),

	T2("t", "t2", "vowel_first"),
	TH("th", "th", "vowel_first"),
	TS("ts", "ts", "vowel_first"),
	TT("tt", "tt", 2, "vowel_first"),
	TZ("tz", "tz", "vowel_first"),
	T_("", "t_", "t2", "th", "ts", "tt", "tz"),

	V2("v", "v_", "vowel_first"),

	W2("w", "w_", "vowel_first"),

	X2("x", "x2", "vowel_first"),
	XT("xt", "xt", "vowel_first"),
	X_("", "x_", "x2", "xt"),

	Z2("z", "z2", "vowel_first"),
	ZZ("zz", "zz", "vowel_first"),
	Z_("", "z_", "z2", "zz"),
	
	UNIVERSAL_FIRST_SYLLABLE("", "universal", 100, "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	DGE("dge", "dge", "a", "e", "i", "o", "u"),
	EL("el", "el", "universal"),
	ING("ing", "ing", "universal"),
	LE("le", "le", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	_R("r", "_r", "a", "e", "i", "o", "u", "le"),
	
	MISC_END("", "misc", "dge", "el", "ing", "le", "_r"),

	//specific suffixes that can follow a digram ending in certain consonants
	ACH("ach", "end", "misc", "universal"),
	ALOV("alov", "end", "universal"),
	ANNE("anne", "end", "misc", "universal"),
	ANOV("anov", "end", "universal"),
	APPA("appa", "end", "universal"),
	ART("art", "end", "misc", "universal"),
	AWAY("away", "end", "misc", "universal"),
	
	BACH("bach", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BAUER("bauer", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BAUM("baum", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BECK("beck", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BERG("berg", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BERRY("berry", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BERT("bert", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BIRD("bird", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BLATT("blatt", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BONNIER("bonnier", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BOO("boo", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BOROUGH("borough", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BORT("bort", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BOTTOMS("bottoms", "end", "a", "e", "i", "o", "misc", "u", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BOURNE("bourne", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BURY("bury", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BURGER("burger", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BRINGER("bringer", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BROOKE("brooke", "end", "a", "e", "i", "o", "u", "misc", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	BY("by", "end", "a", "e", "i", "o", "misc", "u", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	CASTER("caster", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	CHAMP("champ", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	CHESTER("chester", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	CLIFF("cliff", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	COTT("cott", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	COURT("court", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	CRAFT("craft", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	CROIX("croix", "end", "a", "e", "i", "o", "misc", "u", "b_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	DALE("dale", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DATTER("datter", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DELL("dell", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DERF("derf", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DOOF("doof", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DORF("dorf", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	DRAGON("dragon", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	EATER("eater", "end", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	FAX("fax", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FIELD("field", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FINDER("finder", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FISH("fish", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FORD("ford", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FRUIT("fruit", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	FUL("ful", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	GETTE("gette", "end", "a", "e", "i", "o", "u", "dge", "le", "_r", "b_", "c_", "d_", "f_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	GINS("gins", "end", "a", "e", "i", "o", "u", "dge", "le", "_r", "b_", "c_", "d_", "f_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	HAM("ham", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HAZ("haz", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HAMMER("hammer", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HEAD("head", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HEART("heart", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HEIMER("heimer", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HOFF("hoff", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HORN("horn", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	HORT("hort", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "g_", "f_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	IE("ie", "end", "universal"),
	INOV("inov", "end", "universal"),
	ISH("ish", "end", "universal"),

	KAMP("kins", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	KINS("kins", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	KRANTZ("krantz", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	LAND("land", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	LEY("ley", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	LORD("lord", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	MAN("man", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	MAKER("maker", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	MEISTER("meister", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	MEYER("meyer", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	MUFFIN("muffin", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	NARD("nard", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	NEAUX("neaux", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	NER("ner", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	NERD("nerd", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	NORD("nord", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	NUT("nut", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "p_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	
	OE("oe", "end", "universal"),
	OO("oo", "end", "universal"),
	OOEY("ooey", "end", "universal"),

	PANTS("pants", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	PEPPER("pepper", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	POSTER("poster", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),
	POULOS("poulos", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "r_", "s_", "t_", "v_", "w_", "x_", "z_"),

	REICH("reich", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "s_", "t_", "v_", "w_", "x_", "z_"),
	RICH("rich", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "s_", "t_", "v_", "w_", "x_", "z_"),
	ROTH("roth", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "s_", "t_", "v_", "w_", "x_", "z_"),

	SALT("salt", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SHOES("shoes", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SINGER("singer", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SKY("sky", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SLINGER("slinger", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SMITH("smith", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SOCKS("socks", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SON("son", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	SPICE("spice", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	STEIN("stein", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),
	STON("ston", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "t_", "v_", "w_", "x_", "z_"),

	TON("ton", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "v_", "w_", "x_", "z_"),
	THROP("throp", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "v_", "w_", "x_", "z_"),

	VICH("vich", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "w_", "x_", "z_"),

	WALD("wald", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WERTZ("wertz", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WICK("wick", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WIG("wig", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WIN("win", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WITZ("witz", "end", "a", "e", "i", "o", "u", "misc", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WOOD("wood", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WORT("wort", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WORTH("worth", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WRANGLER("wrangler", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WRASSLER("wrassler", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),
	WUMP("wump", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "x_", "z_"),

	Y_END("y", "end", "a", "e", "o", "misc", "universal"),
	YANOV("yanov", "end", "misc", "universal"),

	ZOG("zog", "end", "a", "e", "i", "o", "misc", "u", "b_", "c_", "d_", "f_", "g_", "h_", "j_", "k_", "l_", "m_", "n_", "p_", "r_", "s_", "t_", "v_", "w_", "x_"),
	
	_NOTHING_("", "end", "a_next", "o_next", "misc", "universal"),

	//misc end suffixes
	ACAMOLE("acamole", "end", "u"),
	ADRUNNER("adrunner", "end", "o"),
	ADULUPE("adulupe", "end", "u"),
	AMOFMUSHROOM("amofmushroom", "end", "e"),
	ANDIP("andip", "end", "e"),
	ANUTBUTTER("anutbutter", "end", "e"),
	ARDVARK("ardvark", "end", "a"),
	ARL("arl", "end", "e"),
	ASTBEEF("astbeef", "end", "o"),
	ATBALL("atball", "end", "e"),
	ATMEAL("atmeal", "end", "o"),
	ATRICE("atrice", "end", "e"),
	AVA("ava", "end", "i", "o", "u"),
	AZEBUCKET("azebucket", "end", "e"),
	
	BAGAIL("bagail", "end", "a"),
	BAGANOUSH("baganoush", "end", "a", "o", "u"),
	BALANTE("balante", "end", "a", "e", "i", "o", "u"),
	BAMA("bama", "end", "o"),
	BANERO("banero", "end", "a"),
	BANFOO("banfoo", "end", "a", "e", "i", "o", "u"),
	BASCO("basco", "end", "a"),
	BASTIAN("bastian", "end", "a", "e", "i", "o", "u"),
	BBADON("bbadon", "end", "a", "e", "i", "o", "u"),
	BBERER("bberer", "end", "a", "e", "i", "o", "u"),
	BBERISH("bberish", "end", "a", "e", "i", "o", "u"),
	BBERY("bbery", "end", "a", "e", "i", "o", "u"),
	BBIB("bbib", "end", "a"),
	BBITY("bbity", "end", "a", "e", "i", "o", "u"),
	BBONDONATO("bbondonato", "end", "a"),
	BBOTT("bbott", "end", "a", "e", "i", "o", "u"),
	BDUL("bdul", "end", "a", "e", "i", "o", "u"),
	BEDIAH("bediah", "end", "a", "e", "i", "o", "u"),
	BEDNEGO("bednego", "end", "a", "e", "i", "o", "u"),
	BENEZER("benezer", "end", "e"),
	BERDASH("berdash", "end", "a", "e", "i", "o", "u"),
	BEYE("beye", "end", "i"),
	BIDEEN("bideen", "end", "a", "e", "i", "o", "u"),
	BIO("bio", "end", "a"),
	BISCUS("biscus", "end", "a", "e", "i", "o", "u"),
	BISH("bish", "end", "a", "e", "i", "o", "u"),
	BITHA("bitha", "end", "a", "e", "i", "o", "u"),
	BOLA("bola", "end", "e"),
	BOON("boon", "end", "a"),
	BRAMANIAM("bramaniam", "end", "u"),
	BRAXAS("braxas", "end", "a"),
	BRINA("brina", "end", "a", "e", "i", "o", "u"),
	BRIANA("briana", "end", "a", "e", "i", "o", "u"),
	BRUARY("bruary", "end", "a", "e", "i", "o", "u"),
	BUTICABA("buticaba", "end", "a"),
	BYFACE("byface", "end", "a"),

	CANDCHEESE("candcheese", "end", "a"),
	CACIA("cacia", "end", "a", "e", "i", "o", "u"),
	CAINE("caine", "end", "o"),
	CAMA("cama", "end", "i"),
	CARDO("cardo", "end", "a", "e", "i", "o", "u"),
	CAQUE("caque", "end", "a"),
	CASTE("caste", "end", "a", "o"),
	CATINI("catini", "end", "a", "i", "o", "u"),
	CCIATELLO("cciatello", "end", "a", "e", "i", "o", "u"),
	CCINI("ccini", "end", "a", "e", "i", "o", "u"),
	CEROLA("cerola", "end", "a"),
	CHABOD("chabod", "end", "i"),
	CHARD("chard", "end", "a", "e", "i", "o", "u"),
	CHARY("chary", "end", "a", "e", "i", "o", "u"),
	CHELLE("chelle", "end", "a", "e", "i", "o", "u"),
	CHNOLD("chnold", "end", "a", "e", "i", "o", "u"),
	CHYSOISSE("chysoisse", "end", "i"),
	CIEWEITZ("cieweitz", "end", "a", "e", "i", "o", "u"),
	CKABYE("ckabye", "end", "o", "u"),
	CKADEE("ckadee", "end", "a", "e", "i", "o", "u"),
	CKER("cker", "end", "a", "e", "i", "o", "u"),
	CKERAL("ckeral", "end", "a"),
	CKETT("ckett", "end", "a", "e", "i", "o", "u"),
	CKHEART("ckheart", "end", "a", "e", "i", "o", "u"),
	CKINGBIRD("ckingbird", "end", "a", "e", "i", "o", "u"),
	CKLEY("ckley", "end", "o"),
	CKWHEAT("ckwheat", "end", "u"),
	CNICBASKET("cnicbasket", "end", "a", "e", "i", "o", "u"),
	CODILE("codile", "end", "o"),
	CONUT("conut", "end", "o"),
	CORY("cory", "end", "i"),
	CORICE("corice", "end", "i"),
	CTAVIO("ctavio", "end", "a", "e", "i", "o", "u"),
	CUMBER("cumber", "end", "u"),
	CYCLE("cycle", "end", "i"),
	
	DADDLE("daddle", "end", "e", "i"),
	DAH("dah", "end", "a", "e", "i", "o", "u"),
	DALUPE("dalupe", "end", "a"),
	DARDAR("dardar", "end", "a"),
	DARDUS("dardus", "end", "a", "e", "i", "o", "u"),
	DETTE("dette", "end", "o"),
	DDAD("ddad", "end", "a", "e", "i", "o", "u"),
	DDAM("ddam", "end", "a", "e", "i", "o", "u"),
	DDEUS("ddeus", "end", "a", "e", "i", "o", "u"),
	DDING("dding", "end", "a", "e", "i", "o", "u"),
	DDJOB("ddjob", "end", "o"),
	DELAIDA("delaida", "end", "a"),
	DELAIRE("delaire", "end", "a", "e", "i", "o", "u"),
	DEON("deon", "end", "a", "e", "i", "o", "u"),
	DERICK("derick", "end", "a", "e", "i", "o", "u"),
	DGER("dger", "end", "a", "o"),
	DGERIDOO("dgeridoo", "end", "e", "i"),
	DIBRANCH("dibranch", "end", "u"),
	DICCHIO("diccio", "end", "a"),
	DICULOUS("diculous", "end", "a", "e", "i", "o", "u"),
	DIMIR("dimir", "end", "a", "e", "i", "o", "u"),
	DISON("dison", "end", "a"),
	DITYA("ditya", "end", "a"),
	DLOW("dlow", "end", "a", "e", "i", "o", "u"),
	DOLPH("dolph", "end", "a", "o", "u"),
	DRACH("drach", "end", "a", "o", "u"),
	DSWALLOP("dswallop", "end", "o"),
	DUARDO("duardo", "end", "a", "o", "u"),
	DUH("duh", "end", "a", "e", "i", "o", "u"),
	DYPOO("dypoo", "end", "o", "u"),
	DZILLA("dzilla", "end", "o"),
	
	EBIRD("ubird", "end", "u"),
	EBONE("ebone", "end", "e"),
	EFEATER("efeater", "end", "e"),
	EFUS("efus", "end", "e"),
	EP("ep", "end", "e"),
	EPAK("epak", "end", "e"),
	EPLE("eple", "end", "e"),
	ERIO("erio", "end", "e"),
	ESESTEAK("esesteak", "end", "e"),
	ETCORN("etcorn", "end", "e"),
	EZLEBUB("ezlebub", "end", "e"),
	EZY("ezy", "end", "e"),

	FAEL("fael", "end", "a", "e", "i", "o", "u"),
	FKA("fka", "end", "a", "e", "i", "o", "u"),
	FFALO("ffalo", "end", "a", "e", "i", "o", "u"),
	FFERVESCENCE("ffervescence", "end", "e"),
	FFERSON("fferson", "end", "a", "e", "i", "o", "u"),
	FFERTY("fferty", "end", "a", "e", "i", "o", "u"),
	FFINITY("ffinity", "end", "a", "o", "u"),
	FFONSO("ffonso", "end", "a", "e", "i", "o", "u"),
	FRODITE("frodite", "end", "a"),

	GARFREE("garfree", "end", "u"),
	GARTH("garth", "end", "a", "e", "i", "o", "u"),
	GATHA("gatha", "end", "a"),
	GATRON("gatron", "end", "a", "e", "i", "o", "u"),
	GAWA("gawa", "end", "a", "e", "i", "o", "u"),
	GBIRD("gbird", "end", "i"),
	GDALENA("gdalena", "end", "a", "e", "i", "o", "u"),
	GDANOFF("gdanoff", "end", "a", "e", "i", "o", "u"),
	GEY("gey", "end", "o"),
	GGDROP("ggdrop", "end", "e"),
	GGER("gger", "end", "a", "e", "i", "o", "u"),
	GGINBOTHAM("gginbotham", "end", "a", "e", "i", "o", "u"),
	GGPLANT("ggplant", "end", "e"),
	GHERTY("gherty", "end", "a", "e", "i", "o", "u"),
	GHETTI("ghetti", "end", "a"),
	GHTJAR("ghtjar", "end", "i"),
	GINALD("ginald", "end", "a", "e", "i", "o", "u"),
	GLODYTE("glodyte", "end", "a","o", "u"),
	GMA("gma", "end", "a", "e", "i", "o", "u"),
	GMAC("gmac", "end", "e", "i"),
	GMAROLE("gmarole", "end", "i"),
	GNATIO("gnatio", "end", "a", "e", "i", "o", "u"),
	GNES("gnes", "end", "a"),
	GNIFICANT("gnificant", "end", "i"),
	GOR("gor", "end", "a", "e", "i", "o", "u"),
	GORY("gory", "end", "a", "e", "i", "o", "u"),
	GPIE("gpie", "end", "a"),
	GRIPPA("grippa", "end", "a"),
	GUANA("guana", "end", "a", "e", "i", "o", "u"),
	GUEL("guel", "end", "a", "e", "i", "o", "u"),
	GWUMP("gwump", "end", "a", "e", "i", "o", "u"),

	HAMMAD("hammad", "end", "a", "o", "u"),
	HANNON("hannon", "end", "o"),
	HEMOTH("hemoth", "end", "e"),
	HIO("hio", "end", "o"),
	HJIT("hjit", "end", "a"),
	HLRABI("hlrabi", "end", "o"),

	ID("id", "end", "o"),
	IGLEBOND("iglebond", "end", "e"),
	ILEEN("ileen", "end", "e"),
	INSLEY("insley", "end", "a"),
	IQUIRI("iquiri", "end", "a"),
	ISEDPORK("isedpork", "end", "a"),
	ITBASKET("itbasket", "end", "u"),
	ITCAKE("itcake", "end", "u"),

	JANDRO("jandro", "end", "a", "e", "i", "o", "u"),
	JEED("jandro", "end", "a", "u"),
	JITO("jito", "end", "o"),
	JUBE("jube", "end", "u"),

	KA("ka", "end", "a", "e", "i", "o", "u"),
	KANORI("kanori", "end", "a"),
	KASHA("kasha", "end", "a"),
	KACHU("kachu", "end", "i"),
	KCHOY("kchoy", "end", "o"),
	KEDPOTATO("kedpotato", "end", "a"),
	KEEM("keem", "end", "a"),
	KKAIL("kkail", "end", "i"),
	KOLA("kola", "end", "a", "e", "i", "o", "u"),
	KRA("kra", "end", "a", "o"),
	KURAI("kurai", "end", "a"),

	LABASH("labash", "end", "a"),
	LAF("laf", "end", "o"),
	LAFEL("lafel", "end", "a"),
	LAMARI("lamari", "end", "a"),
	LAMI("lami", "end", "a"),
	LAMONTE("lamonte", "end", "a", "e", "o", "u"),
	LANDA("landa", "end", "a", "e", "i", "o", "u"),
	LANTRO("lantro", "end", "i"),
	LAPENO("lapeno", "end", "a"),
	LARBUS("larbus", "end", "a", "e", "i", "o", "u"),
	LARIO("lario", "end", "a", "e", "i", "o", "u"),
	LARKEY("larkey", "end", "a"),
	LATINOUS("latinous", "end", "e"),
	LAZAR("lazar", "end", "a", "e"),
	LBACORE("lbacore", "end", "a"),
	LBATROSS("lbatross", "end", "a", "e", "i", "o", "u"),
	LBERO("lboro", "end", "a", "e", "i", "o", "u"),
	LBERRY("lberry", "end", "u"),
	LCHER("lcher", "end", "a", "e", "i", "o", "u"),
	LDEBEAST("ldebeast", "end", "e", "i"),
	LDEMAR("ldemar", "end", "a", "e", "i", "o", "u"),
	LDERDASH("lderdash", "end", "a", "e", "i", "o", "u"),
	LDOUS("ldous", "end", "a", "e", "i", "o", "u"),
	LDRICH("ldrich", "end", "a", "e", "i", "o", "u"),
	LDRIN("ldrin", "end", "a"),
	LDWIN("ldwin", "end", "a", "e", "i", "o", "u"),
	LEANOR("leanor", "end", "e"),
	LECTRA("lectra", "end", "e"),
	LEMACHUS("lemachus", "end", "a", "e", "i", "o", "u"),
	LENDULA("lendula", "end", "a"),
	LEPHANT("lephant", "end", "e"),
	LESLAW("leslaw", "end", "o"),
	LESTE("leste", "end", "e"),
	LEXANDER("lexander", "end", "a", "e", "i", "o", "u"),
	LGA("lga", "end", "a", "e", "i", "o", "u"),
	LHOUETTE("lhouette", "i"),
	LIEZER("liezer", "e"),
	LIMANJARO("limanjaro", "end", "i"),
	LFREDO("lfredo", "end", "a", "e", "i", "o", "u"),
	LFRAM("lfram", "end", "a", "e", "i", "o", "u"),
	LGERNON("lgernon", "end", "a", "o", "u"),
	LICAN("lican", "end", "a", "e", "i", "o", "u"),
	LICIOUS("licious", "end", "a", "e", "i", "o", "u"),
	LIA("lia", "end", "a", "e", "i", "o", "u"),
	LIAS("lias", "end", "a", "e", "i", "o", "u"),
	LINDA("linda", "end", "a", "e", "i", "o", "u"),
	LISTAIR("listair", "end", "a"),
	LKNER("lkner", "end", "a", "e", "i", "o", "u"),
	LLABY("llaby", "end", "a"),
	LLACE("llace", "end", "a", "e", "i", "o", "u"),
	LLAGHER("llagher", "end", "a"),
	LLAHAN("llahan", "end", "a"),
	LLBLADDER("llbladder", "end", "a"),
	LLDONE("lldone", "end", "e"),
	LLIAM("lliam", "end", "a", "e", "i", "o", "u"),
	LLIGAN("lligan", "end", "u"),
	LLIGATOR("lligator", "end", "a"),
	LLINAIRE("llinaire", "end", "a", "e", "i", "o", "u"),
	LLSPICE("llspice", "end", "a"),
	LLYGAG("llygag", "end", "o"),
	LOBALO("lobalo", "end", "a"),
	LOCH("loch", "end", "o"),
	LOIS("lois", "end", "a", "e", "i", "o", "u"),
	LOMON("lomon", "end", "o"),
	LONY("lony", "end", "e"),
	LOYSIA("loysia", "end", "a"),
	LPACA("lpaca", "end", "a"),
	LPHOS("lphos", "end", "a", "e", "i", "o", "u"),
	LSAVERDE("lsaverde", "end", "a"),
	LRUS("lrus", "end", "a"),
	LYDE("lyde", "end", "a", "e", "i", "o", "u"),
	LYMPIA("lympia", "end", "o"),


	MADA("mafa", "end", "a"),
	MADEUS("madeus", "end", "a"),
	MAGUCHI("maguchi", "end", "a"),
	MANDCHEESE("mandcheese", "end", "a"),
	MAMOTO("mamoto", "end", "a"),
	MANUEL("manuel", "end", "e"),
	MARAJA("maraja", "end", "a"),
	MARIND("marind", "end", "a"),
	MATILLO("matillo", "end", "o"),
	MATO("mato", "end", "o"),
	MBINO("mbino", "end", "a", "e", "i", "o", "u"),
	MBLY("mbly", "end", "a", "e", "i", "o", "u"),
	MBOO("mboo", "end", "a"),
	MBOREE("mboree", "end", "a", "o", "u"),
	MBURGER("mburger", "end", "a", "e", "i", "o", "u"),
	MBUTAN("mbutan", "end", "a"),
	MBROISA("mbrosia", "end", "a"),
	MEGRANITE("megranite", "end", "o"),
	MELIA("melia", "end", "a"),
	MEMBERT("membert", "end", "a"),
	MENTINE("mentine", "end", "e"),
	MERIGO("merigo", "end", "a"),
	METHYST("methyst", "end", "a"),
	MHERST("mherst", "end", "a", "e", "i", "o", "u"),
	MHOCK("mhock", "end", "a"),
	MICHANGA("michanga", "end", "i"),
	MICHURRI("michurri", "end", "i"),
	MILAH("milah", "end", "a"),
	MILIUS("milius", "end", "a", "e", "i", "o", "u"),
	MILTON("milton", "end", "a"),
	MILY("mily", "end", "e"),
	MINGO("mingo", "end", "a", "e", "i", "o", "u"),
	MINGWAY("mingway", "end", "a", "e", "i", "o", "u"),
	MITRI("mitri", "end", "i"),
	MOGEN("mogen", "end", "i"),
	MONADE("monade", "end", "e"),
	MONGRASS("mongrass", "end", "e"),
	MPANADA("mpanada", "end", "e"),
	MPANELLE("mpanelle", "end", "a"),
	MPANZEE("mpanzee", "end", "i"),
	MPBELL("mpbell", "end", "a"),
	MPERNICKEL("mpernickel", "end", "a", "e", "i", "o", "u"),
	MPKIN("mpkin", "end", "u"),
	MPH("mph", "end", "a", "e", "i", "o", "u"),
	MPHODORUS("mphodorus", "end", "a", "e", "i", "o", "u"),
	MPUS("mpus", "end", "a", "e", "i", "o", "u"),
	MONTE("monte", "end", "a", "e", "i", "o", "u"),
	MQUAT("mquat", "end", "u"),
	MWELT("mwelt", "end", "u"),

	NALD("nald", "end", "a", "e", "i", "o", "u"),
	NALDO("naldo", "end", "a", "e", "i", "o", "u"),
	NANA("nana", "end", "a"),
	NANIGAN("nanigan", "end", "e"),
	NATHAN("nathan", "end", "a", "e", "i", "o", "u"),
	NAULT("nault", "end", "a", "e", "i", "o", "u"),
	NCEL("ncel", "end", "a", "e", "i", "o", "u"),
	NCER("ncer", "end", "a", "e", "i", "o", "u"),
	NCHILADA("nchilada", "end", "e"),
	NCHOVY("nchovy", "end", "a"),
	NCISCO("ncisco", "end", "a", "e", "i", "o", "u"),
	NCUBUS("ncubus", "end", "a", "e", "i", "o", "u"),
	NDARIN("ndarin", "end", "a"),
	NDELION("ndelion", "end", "a"),
	NDERBENDER("nderbender", "end", "e", "i"),
	NDERSON("nderson", "end", "a", "e", "i", "o", "u"),
	NDIANA("ndiana", "end", "a", "e", "i", "o", "u"),
	NDICE("ndice", "end", "a"),
	NDICOOT("ndicoot", "end", "a"),
	NDLER("ndler", "end", "a", "e", "i", "o", "u"),
	NDRASEKAR("ndrasekar", "end", "a"),
	NDREA("ndrea", "end", "a", "e", "i", "o", "u"),
	NDROMEDA("ndromeda", "end", "a"),
	NDWICH("ndwich", "end", "a", "e", "i", "o", "u"),
	NDYCANE("ndycane", "end", "a"),
	NEAPPLE("neapple", "end", "i"),
	NESHRAM("neshram", "end", "a", "e", "i"),
	NEFLU("neflu", "end", "i"),
	NEK("nek", "end", "a", "e", "i", "o", "u"),
	NELLA("nella", "end", "a", "e", "i", "o", "u"),
	NESTRONE("nestrone", "end", "i"),
	NEVIEVE("nevieve", "end", "e", "i"),
	NEYDEW("neydew", "end", "a", "e", "i", "o", "u"),
	NEYMAKER("neymaker", "end", "a", "e", "i", "o", "u"),
	NGFISHER("ngfisher", "end", "a", "e", "i", "o", "u"),
	NGFELLOW("ngfellow", "end", "a", "e", "i", "o", "u"),
	NGA("nga", "end", "a", "e", "i", "o", "u"),
	NGELO("ngelo", "end", "a"),
	NGERBREAD("ngerbread", "end", "i"),
	NGERINE("ngerine", "end", "a"),
	NGO("ngo", "end", "a", "e", "i", "o", "u"),
	NGOSTEEN("ngosteen", "end", "a"),
	NGRID("ngrid", "end", "i"),
	NGUINI("nguini", "end", "i"),
	NGUIN("nguin", "end", "e"),
	NGUS("ngus", "end", "u"),
	NHILDE("nhilde", "end", "a", "e", "i", "o", "u"),
	NICOTTI("nicotti", "end", "a"),
	NILLA("nilla", "end", "a"),
	NIPER("niper", "end", "u"),
	NITZEL("nitzel", "end", "a", "e", "i", "o", "u"),
	NIQUA("niqua", "end", "a", "e", "i", "o", "u"),
	NJAMIN("njamin", "end", "a", "e", "i", "o", "u"),
	NJO("njo", "end", "a", "o", "u"),
	NKLIN("nklin", "end", "a", "e", "i", "o", "u"),
	NKMEYER("nkmeyer", "end", "i"),
	NKO("nko", "end", "a", "e", "i", "o", "u"),
	NKY("nky", "end", "a", "e", "i", "o", "u"),
	NKYKONG("nkykong", "end", "a", "o", "u"),
	NNOCENCE("nnocence", "end", "i"),
	NNAMON("nnamon", "end", "i"),
	NNIBAL("nnibal", "end", "a"),
	NNIFER("nnifer", "end", "a", "e", "i", "o", "u"),
	NNIGAN("nnigan", "end", "a", "e", "i", "o", "u"),
	NNIVA("nniva", "end", "a", "e", "i", "o", "u"),
	NOCEROS("noceros", "end", "i"),
	NOCH("noch", "end", "e"),
	NONDORF("nondorf", "end", "a"),
	NPANYA("npanya", "end", "a"),
	NRIQUE("nrique", "end", "e", "i"),
	NSTON("nston", "end", "a", "e", "i", "o", "u"),
	NTACLAUS("ntaclaus", "end", "a"),
	NTALOPE("ntalope", "end", "a"),
	NTASIA("ntasia", "end", "a"),
	NTONETTE("ntonette", "end", "a", "e", "i", "o", "u"),
	NUMATI("numati", "end", "a"),
	NYA("nya", "end", "a", "e", "i", "o", "u"),
	NZALES("nzales", "end", "a", "e", "i", "o", "u"),
	NZO("nzo", "end", "a", "e", "i", "o", "u"),

	ODCHUCK("odchuck", "end", "o"),
	ODPECKER("odpecker", "end", "o"),
	OFUS("ofus", "end", "o"),
	OGALOO("oogaloo", "end", "o"),
	OK("ok", "end", "o"),
	OKABURRA("okaburra", "end", "o"),
	OLE("ole", "end", "o"),
	OLEY("oley", "end", "o"),
	ONEY("oney", "end", "o"),
	OSBALL("osball", "end", "o"),
	OTHBRUSH("othbrush", "end", "o"),
	OTHPASTE("othpaste", "end", "o"),
	OWULF("owulf", "end", "e"),

	PAYA("paya", "end", "a"),
	PHELIA("phelia", "end", "a", "e", "i", "o", "u"),
	PHIA("phia", "end", "o"),
	PHETH("pheth", "end", "a"),
	PHOMET("phomet", "end", "a"),
	PODILLA("podilla", "end", "a"),
	PORON("poron", "end", "o"),
	PPER("pper", "end", "a", "e", "i", "o", "u"),
	PPERGRINDER("ppergrinder", "end", "e"),
	PPERJACK("pperjack", "end", "e"),
	PPERMINT("ppermint", "end", "e"),
	PPERONCINO("pperoncino", "end", "e"),
	PPET("ppet", "end", "a", "e", "i", "o", "u"),
	PPINGS("ppings", "end", "a", "e", "i", "o", "u"),
	PPLEJACK("pplejack", "end", "a"),
	PPOSSUM("ppossum", "end", "o"),
	PPYCOCK("ppycock", "end", "o"),
	PRICORN("pricorn", "end", "a"),
	PRICOT("pricot", "end", "a"),
	PRIKA("prika", "end", "a"),
	PTISTA("ptista", "end", "a"),
	PTON("pton", "end", "a", "e", "i", "o", "u"),
	PYBARA("pybara", "end", "a"),

	QUAT("quat", "end", "a", "e", "i", "o", "u"),
	QUEFORT("quefort", "end", "a", "o"),
	QUILA("quila", "end", "e"),
	QUITA("shire", "end", "a", "e", "i", "o"),

	RABBA("rabba", "end", "a"),
	RABEAU("rabeau", "end", "a", "e", "i", "o", "u"),
	RAINE("raine", "end", "a", "o"),
	RAMBOLA("rabola", "end", "a", "e", "i", "o", "u"),
	RAPPA("rappa", "end", "a"),
	RARDO("rardo", "end", "a", "e", "i", "o", "u"),
	RATIO("ratio", "end", "a", "e", "i", "o", "u"),
	RAWAY("raway", "end", "a"),
	RAYAN("rayan", "end", "o"),
	RBACOA("rbacoa", "end", "a"),
	RBARA("rbara", "end", "a", "o", "u"),
	RBECUE("rbecue", "end", "a", "o", "u"),
	RCESTER("rcester", "end", "a", "e", "i", "o", "u"),
	RCHIMEDES("rchimedes", "end", "a"),
	RCONE("rcone", "end", "a", "e", "i", "o", "u"),
	RCUPINE("rcupine", "end", "o"),
	RDAMOM("rdamom", "end", "a"),
	RDECAI("rdecai", "end", "o"),
	RDEJO("rdejo", "end", "e", "i"),
	RDELIA("rdelia", "end", "a", "e", "i", "o", "u"),
	RDIGRADE("rdigrade", "end", "a"),
	RDITA("rdita", "end", "o"),
	RDOCK("rdock", "end", "a", "e", "i", "o", "u"),
	REAU("reau", "end", "a", "e", "i", "o", "u"),
	RESCHI("reschi", "end", "a"),
	RFALLE("rfalle", "end", "a"),
	REDITH("redith", "end", "a", "e", "i", "o", "u"),
	REGANO("regano", "end", "o"),
	RFIELD("rfield", "end", "a", "e", "i", "o", "u"),
	RGARET("rgaret", "end", "a", "e", "i", "o", "u"),
	RGARITA("rgarita", "end", "a", "e", "i", "o", "u"),
	RGARINE("rgarine", "end", "a"),
	RGEON("rgeon", "end", "a", "e", "i", "o", "u"),
	RGENOST("rgenost", "end", "e"),
	RGONZOLA("rgonzola", "end", "o"),
	RGUNDY("rgundy", "end", "u"),
	RJORAM("rjoram", "end", "a"),
	RIJUANAS("rijuanas", "a"),
	RIMOYA("rimoya", "end", "e", "i"),
	RIWINKLE("riwinkle", "end", "e"),
	RIZARD("rizard", "end", "a"),
	RKCHOP("rkchop", "end", "o"),
	RLANDO("rlando", "end", "a", "e", "i", "o", "u"),
	RLEMAGNE("rlemagne", "end", "a"),
	RLOS("rlos", "end", "a", "e", "i", "o", "u"),
	RLOTTE("rlotte", "end", "a", "e", "i", "o", "u"),
	RLOV("rlov", "end", "a", "e", "i", "o", "u"),
	RLSBERG("rlsberg", "end", "a", "e", "i", "o", "u"),
	RMALADE("rmalade", "end", "a", "e", "i", "o", "u"),
	RMELO("rmelo", "end", "a", "e", "i", "o", "u"),
	RMESAN("rmesan", "end", "a"),
	RMICELLI("rmicelli", "end", "e"),
	RMINE("rmine", "end", "a", "e"),
	RMORANT("rmorant", "end", "o"),
	RMOT("rmot", "end", "a"),
	RMSTRONG("rmstrong", "end", "a"),
	RNABUS("rnabus", "end", "a", "e", "i", "o", "u"),
	RNAISE("rnaise", "end", "a", "e", "i", "o", "u"),
	RNANDO("rnando", "end", "a", "e", "i", "o", "u"),
	RNARD("rnard", "end", "a", "e", "i", "o", "u"),
	RNELIUS("rnelius", "end", "a", "e", "i", "o", "u"),
	RNFLAKES("rnflakes", "end", "o"),
	RNIP("rnip", "end", "u"),
	RNITAS("rnitas", "end", "a"),
	RNSWOGGLE("rnswoggle", "end", "o"),
	ROCHE("roche", "end", "a"),
	RONA("rona", "end", "a", "e", "i", "o", "u"),
	RONICA("ronica", "end", "a", "e", "i", "o", "u"),
	RORO("roro", "end", "a", "e", "i", "o", "u"),
	RPACCIO("rpaccio", "end", "a"),
	RPO("rpo", "end", "a", "e", "i", "o", "u"),
	RRACUDA("rracuda", "end", "a"),
	RRASCO("rrasco", "end", "a", "o", "u"),
	RRAULT("rrault", "end", "a", "e", "i", "o", "u"),
	RREAU("rreau", "end", "a", "e", "i", "o", "u"),
	RRITO("rrito", "end", "u"),
	RROWAY("rroway", "end", "a", "e", "i", "o", "u"),
	RSCHT("rscht", "end", "o"),
	RSERADISH("rseradish", "end", "o"),
	RSHMALLOW("arshmallow", "end", "a"),
	RSIMMON("rsimmon", "end", "e"),
	RSLEY("rsley", "end", "a"),
	RSNIP("rsnip", "end", "a"),
	RSULA("rsula", "end", "a", "e", "i", "o", "u"),
	RTALOTTI("rtalotti", "end", "a"),
	RTELLINI("rtellini", "end", "o"),
	RTINBRAS("rtinbras", "end", "o"),
	RTHOLOMEW("rtholomew", "end", "a", "e", "i", "o", "u"),
	RTICHOKE("rtichoke", "end", "a"),
	RTICUS("rticus", "end", "a", "o", "u"),
	RTIER("rtier", "end", "a", "e", "i", "o", "u"),
	RTILLA("rtilla", "end", "o"),
	RTOISE("rtoise", "end", "o", "u"),
	RTOLI("rtoli", "end", "a", "e", "i", "o", "u"),
	RTOUR("rtour", "end", "a", "e", "i", "o", "u"),
	RTRAND("rtrand", "end", "a", "e", "i", "o", "u"),
	RTRIDGE("rtridge", "end", "a"),
	RTUNATA("rtunata", "end", "o"),
	RUCH("ruch", "end", "a"),
	RUGULA("rugula", "end", "a"),
	RVETTE("rvette", "end", "o"),
	RWHAL("rwhal", "end", "a"),
	RYL("ryl", "end", "a", "e", "i", "o", "u"),
	RZIPAN("rzipan", "end", "a"),
	RZVLAK("rzvlak", "end", "a", "e", "i", "o", "u"),

	SAAC("saac", "end", "i"),
	SABELLA("sabella", "end", "a", "e", "i", "o", "u"),
	SADORA("sadora", "end", "a", "e", "i", "o", "u"),
	SAGNA("sagna", "end", "a"),
	SARIO("sario", "end", "o"),
	SCARGOT("scargot", "end", "e"),
	SCOE("scoe", "end", "a", "e", "i", "o", "u"),
	SDEMEANOR("sdemeanor", "end", "i"),
	SEIDON("seidon", "end", "o"),
	SEMARY("semary", "end", "o"),
	SERUP("serup", "end", "o"),
	SEVELT("sevelt", "end", "a", "e", "i", "o", "u"),
	SHINI("shini", "end", "a", "e", "i", "o", "u"),
	SHIRE("shire", "end", "a", "e", "i", "o", "u"),
	SHMAEL("shmael", "end", "a", "e", "i", "o", "u"),
	SHMERE("shmere", "end", "a"),
	SHNU("shnu", "end", "i"),
	SHUA("shua", "end", "o"),
	SHWACKER("shwacker", "end", "u"),
	SIMIR("simir", "end", "a"),
	SMODEL("smodel", "end", "a"),
	SPANOVA("spanova", "end", "a", "e", "i", "o", "u"),
	SPAR("spar", "end", "a"),
	SPARAGUS("sparagus", "end", "a"),
	SPUS("spus", "end", "a", "e", "i", "o", "u"),
	SRAEL("srael", "end", "e", "i"),
	SSAFRAS("ssafras", "end", "a"),
	SSAIN("ssain", "end", "a", "u"),
	SSARIAN("ssarian", "end", "a", "o", "u"),
	SSAVA("ssava", "end", "a"),
	SSICA("ssica", "end", "e"),
	SSIE("ssie", "end", "a", "e", "i", "o", "u"),
	SSILI("ssili", "end", "u"),
	SSINI("ssini", "end", "a", "e", "i", "o", "u"),
	STACHIO("stachio", "end", "i"),
	STADA("stada", "end", "o"),
	STAFA("stafa", "end", "o","u"),
	STANTE("stante", "end", "a", "e", "i", "o", "u"),
	STARD("stard", "end", "a", "e", "i", "o", "u"),
	STAROSSA("starossa", "end", "e"),
	STEBAN("steban", "end", "a", "e", "i", "o", "u"),
	STOPHER("stopher", "end", "a", "e", "i", "o", "u"),
	STULE("stule", "end", "a", "e", "i", "o", "u"),

	TABAGA("tabaga", "end", "u"),
	TALINI("talini", "end", "a", "e", "i", "o", "u"),
	TANGA("tanga", "end", "a", "e", "i", "o", "u"),
	TANNIA("tannia", "end", "a", "e", "i", "o", "u"),
	TATO("tato", "end", "a", "o"),
	TATRON("tatron", "end", "a", "e", "i", "o", "u"),
	TCHEROO("tcheroo", "end", "i"),
	TCHOCOLATE("tchocolate", "end", "o"),
	TCOIN("tcoin", "end", "i"),
	TERMELON("termelon", "end", "a"),
	THELLO("thello", "end", "o"),
	THERFORD("therford", "end", "a", "e", "i", "o", "u"),
	THIUM("thium", "end", "a", "e", "i", "o", "u"),
	THRO("thro", "end", "a", "e", "i", "o", "u"),
	THESHEBA("thesheba", "end", "a", "e", "i", "o", "u"),
	TICIA("ticia", "end", "a", "e", "i", "o", "u"),
	TMEG("tmeg", "end", "u"),
	TNEY("tney", "end", "i", "u"),
	TNIP("tnip", "end", "a"),
	TONIO("tonio", "end", "a", "e", "i", "o", "u"),
	TTA("tta", "end", "a", "e", "i", "o", "u"),
	TTERMELON("ttermelon", "end", "i"),
	TTICELLI("tticelli", "end", "a", "e", "i", "o", "u"),
	TTICINI("tticini", "end", "a", "e", "i", "o", "u"),
	TTICUS("tticus", "end", "a", "e", "i", "o", "u"),
	TTONCHOPS("ttonchops", "end", "o", "u"),
	TTERCUPS("ttercups", "end", "o", "u"),

	UBLEDAY("ubleday", "end", "o"),
	UCLID("uclid", "end", "e"),
	UGENE("ugene", "end", "e"),
	UHAHA("uhaha", "end", "o"),
	UILLABAISSE("uillabiasse", "end", "o"),
	UILLON("uillon", "end", "o"),
	ULASH("ulash", "end", "o"),
	ULIFLOWER("uliflower", "end", "a"),
	USAGE("usage", "end", "a"),
	URDOUGH("urdough", "end", "o"),
	UTILUS("utilus", "end", "a"),

	VABEAN("vabean", "end", "a"),
	VACADO("vacado", "end", "a"),
	VANAUGH("vanaugh", "end", "a"),
	VENGELINE("vangeline", "end", "e"),
	VERETT("verett", "end", "a", "e", "i", "o", "u"),
	VARIUS("varius", "end", "a", "e", "i", "o", "u"),
	VATAPPI("vatappi", "end", "a"),
	VECRAFT("vecraft", "end", "o"),
	VELIER("velier", "end", "a", "e", "i", "o", "u"),
	VENDER("vender", "end", "a"),
	VERGREEN("vergreen", "end", "e"),
	VERLORD("verlord", "end", "o"),
	VIKA("vika", "end", "a", "a", "e", "i", "o", "u"),
	VINGTON("vington", "end", "a", "e", "i", "o", "u"),
	VINSKY("vinsky", "end", "a", "e", "i", "o", "u"),
	VIOLI("violi", "end", "a"),
	VITICUS("viticus", "end", "e"),

	WDER("wder", "end", "o"),
	WENHOEK("wenhoek", "end", "a", "e", "i", "o", "u"),
	WIFRUIT("wifruit", "end", "i"),
	WLER("wler", "end", "o"),
	WTHORNE("wthorne", "end", "a"),
	WYER("wyer", "end", "a", "o"),
	
	XANNE("xanne", "end", "a", "e", "i", "o", "u"),
	XFORD("xford", "end", "a", "e", "i", "o", "u"),
	XIMUS("ximus", "end", "a", "e", "i", "o", "u"),
	XLEY("xley", "end", "u"),
	XTER("xter", "end", "a", "e", "i", "o", "u"),

	YAMOTO("yamoto", "end", "i"),
	YARDEE("yardee", "end", "o"),
	YENNE("yenne", "end", "a"),
	YLEE("ylee", "end", "a"),
	YOKO("yoko", "end", "i"),
	YONNAISE("yonnaise", "end", "a"),
	YOTE("yote", "end", "a"),

	ZAEMON("zaemon", "end", "o"),
	ZARUS("zarus", "end", "a", "e", "i", "o", "u"),
	ZAZEL("zazel", "end", "a"),
	ZEBEL("zebel", "end", "a", "e", "i", "o", "u"),
	ZEKIEL("zekiel", "end", "a", "e", "i", "o", "u"),
	ZERAC("zerac", "end", "a"),
	ZMA("zma", "end", "a", "e", "i", "o", "u"),
	ZMO("zmo", "end", "a", "e", "i", "o", "u"),
	ZPACHO("zpacho", "end", "a"),
	ZZAPIE("zzapie", "end", "i"),
	ZZERELLA("zzerella", "end", "o"),

	;
	
	//This name and the end of this name fragment
	private final String me, endTag;
	
	//how likely is this segment to follow any of its predecessors?
	private final int weight;
	
	//A list of name fragments that this name fragment can follow.
	private final String[] canFollow;
	
	NameGenerator(String me, String endTag, int weight, String... canFollow) {
		this.me = me;
		this.endTag = endTag;
		this.weight = weight;
		this.canFollow = canFollow;
	}
	
	NameGenerator(String me, String endTag, String... canFollow) {
		this(me, endTag, 1, canFollow);
	}
	
	/**
	 * @param alliteration: Should the 2 names have the same first letter?
	 * @return a generated first and last name.
	 */
	public static String generateFirstLast(boolean alliteration) {
		
		ArrayList<NameGenerator> possibleNexts = new ArrayList<>();

		for (NameGenerator gen: NameGenerator.values()) {
			for (int i = 0; i < gen.canFollow.length; i++) {
				if (gen.canFollow[i].equals("start")) {
					for (int j = 0; j < gen.weight; j++) {
						possibleNexts.add(gen);
					}
				}
			}
		}
		
		int randomIndex = GameStateManager.generator.nextInt(possibleNexts.size());
		NameGenerator next1 = possibleNexts.get(randomIndex);
		NameGenerator next2 = alliteration ? possibleNexts.get(randomIndex) : possibleNexts.get(GameStateManager.generator.nextInt(possibleNexts.size()));
		
		String firstName = next1.me + generateName(next1.endTag);
		String lastName = next2.me + generateName(next2.endTag);
		
		firstName = firstName.substring(0, 1).toUpperCase() + firstName.substring(1);
		lastName = lastName.substring(0, 1).toUpperCase() + lastName.substring(1);
		return firstName + " " + lastName;
	}
	
	/**
	 * Base Case for recursive name generation.
	 * Start with a name fragment with a "start" tag
	 */
	public static String generateName() {
		return generateName("start");
	}
	
	/**
	 * Recursive case. Randomly select a valid next name fragment
	 * @param prev: The name so far
	 * @return The generated name fragment, plus the rest of the name
	 */
	public static String generateName(String prev) {
		
		ArrayList<NameGenerator> possibleNexts = new ArrayList<>();
		
		//identify all possible next name fragments
		for (NameGenerator gen: NameGenerator.values()) {
			for (int i = 0; i < gen.canFollow.length; i++) {
				if (gen.canFollow[i].equals(prev)) {
					for (int j = 0; j < gen.weight; j++) {
						possibleNexts.add(gen);
					}
				}
			}
		}
		
		if (possibleNexts.isEmpty()) { return ""; }
		
		//pick a random possibly next fragment and add it.
		int randomIndex = GameStateManager.generator.nextInt(possibleNexts.size());
		NameGenerator next = possibleNexts.get(randomIndex);
		
		if (next.endTag.equals("end")) {
			return next.me;
		} else {
			return next.me + generateName(next.endTag);
		}
	}
}
